### ISSUE TITLE
Run a single datapoint

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#22]
Add functionality to specify a single datapoint to run (rerun).  This would look like the current run method, except that an additional featureID argument could be specified. If present, run only that one (and don't delete everything in the scenario), if not present, run everything.   Postprocess method would stay as is.

Requested by Sammy

**Comment by vtnate** [comment]
This was also requested by Joe on Feb 17, 2020

**Comment by tanushree04** [comment]
I can take a pass at addressing this.

**Comment by vtnate** [comment]
Great, thanks @tanushree04. Let me know when you've got something, so I can help integrate it into the CLI

**Comment by vtnate** [comment]
@kflemin Our current idea is to build a new ScenarioCSV file with only a single feature when this is called with the CLI. Then the user would call the run command as normal, using the newly created scenarioCSV file that only has a single feature in it. Will this workflow be acceptable?
