### ISSUE TITLE
Using weekday start time in example mapper

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#26]
For reference:
The following inputs from the building schema:
- weekday_start_time
- weekday_duration
- weekend_start_time
- weekend_duration

Should be mapped to inputs for the new create_typical measure (https://github.com/NREL/openstudio-model-articulation-gem/tree/bonnema/add/lib/measures/create_typical_doe_building_from_model).

Note that the start_time arguments are stored as times in the schema but should be converted to doubles when passed to the measure, example:  8:30am should be 8.5, 1:30pm should be 13.5.

It would be nice to update the example files to a) use this new measure b) map the arguments correctly.  This can be done when the measure is released in the new model_articulation gem version.

**Comment by vtnate** [comment]
@tanushree04 Will you work with me on this issue?

**Comment by tanushree04** [comment]
@vtnate Yes, we can work on this one together.
