### ISSUE TITLE
Residential enhancements to support modeling a disadvantaged community

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#295]
Residential - enhancements to represent actual consumption of a (disadvantaged) community.  

- heating only / no AC: this is already available by selecting "system_type" in the geojson file. There's an option for "Residential - electric resistance and no cooling"

- no dishwasher/dryer (removing major appliances): we can currently edit info related to this in the residential TSV files (can add more rows and use the 'template' key in the geojson file to select the row.  In terms of removing appliances, we would have to add a "skip_dishwasher" key in geojson to skip adding that appliance. would want to add a key for each major appliance (dishwasher, clothes dryer, clothes washer. anything else?)

- refrigeration efficiency: can be modified in refrigeration tsv (add a new row and key in with the template value in geojson file or directly edit the current row in the tsv in your project dir. 

-  DHW flowrate or flow rate per occupant and occupant number - water_fixtures_usage_multiplier can be set in TSV file

**Comment by joseph-robertson** [comment]
On the second item, it's possible to avoid modeling appliances by editing the residential TSV files. This would only be useful if you wanted the same behavior for all residential features. For example, by adding a `clothes_washer_location` column that maps to 'none': https://github.com/urbanopt/urbanopt-example-geojson-project/blob/develop/example_project/resources/hpxml-measures/BuildResidentialHPXML/measure.rb#L2283-L2303

**Comment by kflemin** [comment]
thanks for the clarification @joseph-robertson !  We could also modify the "template" and add a row to the file to do this for some buildings and not others, right?  (ex: a Sep 2020 column that adds a clothes washer and a Feb 2022 that has it set to "none")

**Comment by joseph-robertson** [comment]
That's true.

**Comment by wta12** [comment]
@joseph-robertson : Is is relative easy to increase DHW flowrate or flow rate per occupant and occupant number with HPXML workflow ? We observed high usage of DHW due to many people live in same building in UCI project. It's great if just change def value with real number
