### ISSUE TITLE
Support bring your own HPXML to allow full customization in UO workflow

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#296]
Project sometimes have HPXML files, quickest path to accurate models will be to use these HPXML files instead of generating HPXML files from info in GeoJSON. Will use existing code to convert HPXML to OSM and merge to single OSM per feature

**Comment by DavidGoldwasser** [comment]
@joseph-robertson is this ready to close, or should be leave open, Is there documentation task left for this?
