### ISSUE TITLE
Residential enhancements to enable modifications by # of occupants

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#297]
Support residential adjustments based on number of occupants (rather than assets)

ResStock already has controls to make calculations based on #occupants instead of #bedrooms. Could expose this in geojson file: #occupants input, and then a boolean input for ""apply occupancy adjustments"", and then modify the measure to add the ResStock calculations (~1wk effort, issue #644 on OS-HPXML repo)"

**Comment by joseph-robertson** [comment]
Checklist:
- [ ] urbanopt-geojson-gem
  - [ ] add optional integer `number_of_occupants` field for residential types
  - [ ] add optional boolean `apply_occupancy_adjustments` field for residential types
- [ ] urbanopt-example-geojson-project
  - [ ] `example_project_combined.json`: update 1 or more residential features with new fields
  - [ ] `Baseline.rb`:
    - [ ] assume occupants equals bedrooms if not specified
    - [ ] divide building number of occupants by building number of units
    - [ ] adjust mulltipliers based on occupants (see [ResStockArguments](https://github.com/NREL/resstock/blob/develop/measures/ResStockArguments/measure.rb) measure)
  - [ ] `BuildResidentialModel.rb`: no changes I think. stochastic schedules are a function of occupants: you specify occupants, it's based on that. if you don't, old behavior (based on bedrooms).
- [ ] urbanopt-cli
  - [ ] copy relevant files over
- [ ] urbanopt.net
  - [ ] `Residential Workflows`: update documentation, schema tables, feature examples, etc.
