### ISSUE TITLE
Create URBANopt-DISCO input cost database

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-cli#338]
- Expand on the RNM cost database to include any additional fields required by DISCO.
- Format it for DISCO.
- This would live in the URBANopt-cli repo

DISCO technical catalogue: https://github.com/NREL/disco/blob/main/disco/extensions/upgrade_simulation/upgrades/smartds_upgrades_technical_catalog.json

DISCO cost database: https://github.com/NREL/disco/blob/main/disco/extensions/upgrade_simulation/upgrades/Generic_DISCO_cost_database_v2.xlsx

**Comment by kflemin** [comment]
@tarekelgindy, I think this work has no dependencies and could be started whenever you have time
