### ISSUE TITLE
scenario run with customised Residential features 

### ISSUE THREAD

**Issue by Francesca-urbanplanner** [urbanopt/urbanopt-cli#364]
### Expected behavior
Run scenarios and obtain results for single buildings, having buildings (residential) and weather files for Toronto. 

### Actual behavior
After running the [scenario], the result is the following one:
![problem](https://user-images.githubusercontent.com/108810715/177565806-8439ee9c-be3b-4216-8a1f-63c42d8c91eb.jpeg)
and the run folder/baseline scenario is empty

### To Reproduce

1. uo create --empty --project-folder <path/to/PROJECT_DIRECTORY_NAME> -d
here, i've added a folder "weather" with CAN_ON_Toronto.716240_CWEC.epw + runner.conf
2. uo create --scenario-file <path/to/FEATUREFILE.json>
3.  uo run --feature <path/to/FEATUREFILE.json> --scenario <path/to/SCENARIOFILE.csv>

_E.g.: Windows, Mac, Linux? Are you behind a firewall? Do you have additional security constraints?_

**Comment by Francesca-urbanplanner** [comment]
@kflemin thank you for your help. I ve checked again the feature geojson file and it looks in the right location. But still, the scenario run shows the following error:
![image](https://user-images.githubusercontent.com/108810715/177797130-600a537f-d8e7-49d7-bc54-6dec39d54bca.png)
![image](https://user-images.githubusercontent.com/108810715/177797296-37fa28cd-4bf0-4038-83bd-187f2e46f676.png)
(and plus, despite having only single detached and attached residential types, it mentions undefined number_of_residential_units even if they are not required).

**Comment by kflemin** [comment]
@Francesca-urbanplanner I no longer see errors related to the weather filename in the latest screenshots so maybe that part is resolved.

Now I see some issues with 'number_of_residential_units' missing on some features...that key is required and validated on Multifamily and Single-Family Attached building types: 
https://github.com/urbanopt/urbanopt-cli/blob/v0.8.0/example_files/mappers/Baseline.rb#L649-L651
Perhaps you have some single family attached buildings missing that key?

**Comment by joseph-robertson** [comment]
From https://docs.urbanopt.net/, I see that `number_of_residential_units` is required for both [single-family attached](https://docs.urbanopt.net/workflows/residential_workflows/single_family_attached.html#geojson-schema) and [low-rise multifamily](https://docs.urbanopt.net/workflows/residential_workflows/multifamily.html#geojson-schema) residential building types.

Indeed feature `id=17` (i.e., a single-family attached building) from `example_project_combined.json` does not have `number_of_residential_units` populated. This is because it has the `hpxml_directory` field populated which points to a folder containing an HPXML file for each of its 4 units. See [here](https://github.com/urbanopt/urbanopt-example-geojson-project/tree/develop/example_project/xml_building/17) for more information.

**Comment by Francesca-urbanplanner** [comment]
thank you for your help! i think there was a problem with the template I've added in the Feature File. 
For residential buildings, do the "Residential IECC 20XX - Customizable Template Sep 202X" template support detached, attached and multifamily?

**Comment by kflemin** [comment]
All of the residential templates listed here:

https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/urbanopt/geojson/schema/building_properties.json#L482-L491

should support the building types here: 
https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/urbanopt/geojson/schema/building_properties.json#L302-L304

Make sure that you do not use the old building types listed here as they will not work with the residential templates and will instead go through the commercial workflow (they are only there for backward compatibility with old versions of UO)
https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/lib/urbanopt/geojson/schema/building_properties.json#L305-L307

hope this helps!

**Comment by kflemin** [comment]
if you can paste just one of these failing buildings' geojson section, I can see if I can get it running. you could also try the newest urbanopt release (v0.8.2).

**Comment by Francesca-urbanplanner** [comment]
I've just copied and pasted a couple of buildings from the geojson file. 
I've tried different options:
1. change the default template with the "Residential IECC 2018 - Customizable Template Sep 2020"
2.  insert the "Residential IECC 2018 - Customizable Template Sep 2020" template only for single detached and attached, while leaving the "90.1-2019" for multi-family types
However, none of them has worked so far. 

{
    "type": "FeatureCollection",
    "mappers": [],
    "project": {
      "id": "7c33a001-bccb-413e-ac87-67558b5d4b07",
      "name": "New Project",
      "begin_date": "2017-01-01T07:00:00.000Z",
      "end_date": "2017-12-31T07:00:00.000Z",
      "cec_climate_zone": null,
      "climate_zone": "6A",
      "default_template": "90.1-2019",
      "import_surrounding_buildings_as_shading": true,
      "surface_elevation": null,
      "tariff_filename": null,
      "timesteps_per_hour": 1,
      "weather_filename": "CAN_ON_Toronto.716240_CWEC.epw"
    },
    "scenarios": [
      {
        "feature_mappings": [],
        "id": "72301739-c6c3-4dd7-bf1a-f37c8eff40db",
        "name": "New Scenario"
      }
    ],
    "features": [
      {
        "type": "Feature",
        "properties": {
          "id": "53340c2c-ab20-40db-aba1-11ac607c52a7",
          "name": "Site Origin",
          "type": "Site Origin",
          "begin_date": "2017-01-01T07:00:00.000Z",
          "end_date": "2017-12-31T07:00:00.000Z",
          "cec_climate_zone": null,
          "climate_zone": "6A",
          "default_template": "90.1-2019",
          "import_surrounding_buildings_as_shading": true,
          "surface_elevation": null,
          "tariff_filename": null,
          "timesteps_per_hour": 1,
          "weather_filename": "CAN_ON_Toronto.716240_CWEC.epw"
        },
        "geometry": {
          "type": "Point",
          "coordinates": [
            -78.84948467732347,
            42.81677154451123
          ]
        }
      },

      {
        "type": "Feature",
        "id": 0,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                1595842.3247717714,
                4926072.889435685
              ],
              [
                1595844.7441362701,
                4926074.060764929
              ],
              [
                1595843.2274531412,
                4926077.1929968055
              ],
              [
                1595840.7954767223,
                4926076.015871409
              ],
              [
                1595839.4041543102,
                4926078.890817441
              ],
              [
                1595837.2821953744,
                4926083.273900675
              ],
              [
                1595837.1832143404,
                4926083.478784426
              ],
              [
                1595839.2564726688,
                4926084.4824505765
              ],
              [
                1595839.0293349216,
                4926084.951547944
              ],
              [
                1595837.106592566,
                4926088.924559913
              ],
              [
                1595836.9825664833,
                4926089.181231892
              ],
              [
                1595835.4462099008,
                4926088.43732433
              ],
              [
                1595833.3564131754,
                4926092.755303202
              ],
              [
                1595833.2994623191,
                4926092.872961315
              ],
              [
                1595825.556085257,
                4926089.125520512
              ],
              [
                1595825.8983892458,
                4926088.418436868
              ],
              [
                1595820.9259360926,
                4926086.011678098
              ],
              [
                1595820.6038721506,
                4926085.957025734
              ],
              [
                1595820.9154026508,
                4926085.313942939
              ],
              [
                1595816.73605294,
                4926083.291292676
              ],
              [
                1595818.2882396688,
                4926080.084021118
              ],
              [
                1595818.4215905578,
                4926079.808328511
              ],
              [
                1595819.0194225186,
                4926080.097525909
              ],
              [
                1595821.1773366644,
                4926075.638971073
              ],
              [
                1595823.2764311272,
                4926071.3018456735
              ],
              [
                1595825.9184987284,
                4926072.581273259
              ],
              [
                1595827.0022846153,
                4926070.342697838
              ],
              [
                1595824.6563306828,
                4926069.207407331
              ],
              [
                1595825.0337336347,
                4926068.427556966
              ],
              [
                1595826.5802469605,
                4926065.232004636
              ],
              [
                1595826.7578918512,
                4926064.8653377425
              ],
              [
                1595826.9249458693,
                4926064.520361241
              ],
              [
                1595829.284958835,
                4926065.630419912
              ],
              [
                1595842.6835924704,
                4926072.147223126
              ],
              [
                1595842.3247717714,
                4926072.889435685
              ]
            ]
          ]
        },
        "properties": {
          "FID": 0,
          "number_of_stories_above_ground": 2,
          "name": "B5840",
          "floor_area": 13348.2070256,
          "footprint_area": 4449.40234187,
          "number_of_stories": 3,
          "number_of_bedrooms": 9,
          "attic_type":"attic - vented",
          "foundation_type": "basement - conditioned",
          "roof_type": "Gable",
          "number_of_occupants": 9,
          "system_type": "Residential - furnace and no cooling",
          "heating_system_fuel_type": "natural gas",
          "building_type":"Single-Family Attached",
          "year_built": 1980,
          "id": "840",
          "type": "Building",
          "building_status": "Existing",
          "footprint_perimeter": 320.830324389,
          "emissions": true,
          "number_of_residential_units": 3,
          "exterior_lighting_zone": "3 - All Other Areas",
          "emissions_future_subregion": "RFCEc",
          "emissions_hourly_historical_subregion": "New York",
          "emissions_annual_historical_subregion": "RFCE",
          "emissions_future_year": "2022",
          "emissions_hourly_historical_year": "2019",
          "emissions_annual_historical_year": "2019",
          "template": "Residential IECC 2018 - Customizable Template Sep 2020"
        }
      },
      {
        "type": "Feature",
        "id": 58,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                1595778.2763992907,
                4926155.319414302
              ],
              [
                1595780.3192558815,
                4926151.069735794
              ],
              [
                1595783.3525284731,
                4926152.441788858
              ],
              [
                1595787.5080420228,
                4926144.048619869
              ],
              [
                1595800.3485056395,
                4926150.2629433675
              ],
              [
                1595796.4812037717,
                4926158.251435179
              ],
              [
                1595797.9727661153,
                4926158.973922314
              ],
              [
                1595798.5101998858,
                4926160.835937074
              ],
              [
                1595797.2718579415,
                4926163.279578274
              ],
              [
                1595795.2503741458,
                4926164.028178988
              ],
              [
                1595788.863022417,
                4926160.936759127
              ],
              [
                1595790.5746133064,
                4926157.512407928
              ],
              [
                1595785.5480489281,
                4926154.9027443435
              ],
              [
                1595783.9631875695,
                4926158.071489118
              ],
              [
                1595778.2763992907,
                4926155.319414302
              ]
            ]
          ]
        },
        "properties": {
          "FID": 58,
          "number_of_stories_above_ground": 3,
          "name": "B7345",
          "floor_area": 9312.43075868,
          "footprint_area": 2328.10768967,
          "number_of_stories": 4,
          "number_of_bedrooms": 3,
          "attic_type":"attic - vented",
          "foundation_type": "basement - conditioned",
          "roof_type": "Gable",
          "number_of_occupants": 3,
          "system_type": "Residential - furnace and no cooling",
          "heating_system_fuel_type": "natural gas",
          "building_type":"Single-Family Attached",
          "year_built": 1980,
          "id": "1487",
          "type": "Building",
          "building_status": "Existing",
          "footprint_perimeter": 247.669048732,
          "emissions": true,
          "number_of_residential_units": 4,
          "exterior_lighting_zone": "3 - All Other Areas",
          "emissions_future_subregion": "RFCEc",
          "emissions_hourly_historical_subregion": "New York",
          "emissions_annual_historical_subregion": "RFCE",
          "emissions_future_year": "2022",
          "emissions_hourly_historical_year": "2019",
          "emissions_annual_historical_year": "2019",
          "template": "Residential IECC 2018 - Customizable Template Sep 2020"
        }
      },
      {
        "type": "Feature",
        "id": 50,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                1595784.7656091568,
                4926163.303965876
              ],
              [
                1595782.312308639,
                4926162.116751743
              ],
              [
                1595783.676182511,
                4926159.298219705
              ],
              [
                1595783.788751033,
                4926159.065972475
              ],
              [
                1595786.3418235949,
                4926160.30140827
              ],
              [
                1595798.7152538556,
                4926166.309510274
              ],
              [
                1595799.5140748043,
                4926166.676465603
              ],
              [
                1595797.4180983303,
                4926171.007001853
              ],
              [
                1595796.6516301564,
                4926170.635951853
              ],
              [
                1595796.4020470174,
                4926171.151099671
              ],
              [
                1595796.2694289421,
                4926171.424857451
              ],
              [
                1595783.7646843512,
                4926165.372766603
              ],
              [
                1595784.7656091568,
                4926163.303965876
              ]
            ]
          ]
        },
        "properties": {
          "FID": 50,
          "number_of_stories_above_ground": 1,
          "name": "B6369",
          "floor_area": 992.668230129,
          "footprint_area": 992.668230129,
          "number_of_stories": 1,
          "number_of_bedrooms": 1,
          "attic_type":"flat roof",
          "foundation_type": "ambient",
          "number_of_occupants": 1,
          "system_type": "Residential - boiler and central air conditioner",
          "heating_system_fuel_type": "natural gas",
          "building_type":"Multifamily",
          "year_built": 1980,
          "id": "1184",
          "type": "Building",
          "building_status": "Existing",
          "footprint_perimeter": 151.951304433,
          "emissions": true,
          "number_of_residential_units": 1,
          "exterior_lighting_zone": "3 - All Other Areas",
          "emissions_future_subregion": "RFCEc",
          "emissions_hourly_historical_subregion": "New York",
          "emissions_annual_historical_subregion": "RFCE",
          "emissions_future_year": "2022",
          "emissions_hourly_historical_year": "2019",
          "emissions_annual_historical_year": "2019",
          "template": "Residential IECC 2018 - Customizable Template Sep 2020"
        }
      },
      {
        "type": "Feature",
        "id": 73,
        "geometry": {
          "type": "Polygon",
          "coordinates": [
            [
              [
                1595795.3732872137,
                4925919.312589556
              ],
              [
                1595798.5418131684,
                4925912.6096834205
              ],
              [
                1595800.5988830382,
                4925913.605847813
              ],
              [
                1595802.8711672868,
                4925914.680889125
              ],
              [
                1595811.6863411507,
                4925918.847180174
              ],
              [
                1595814.0974544734,
                4925920.015173653
              ],
              [
                1595813.9392658796,
                4925920.348869277
              ],
              [
                1595814.5580978214,
                4925920.641730263
              ],
              [
                1595814.8844793362,
                4925922.350483842
              ],
              [
                1595814.0878774528,
                4925924.03447742
              ],
              [
                1595812.4432846778,
                4925924.996832153
              ],
              [
                1595811.7872466228,
                4925924.686488895
              ],
              [
                1595811.6893357711,
                4925924.8923791805
              ],
              [
                1595809.2818297413,
                4925923.857638866
              ],
              [
                1595808.4674550565,
                4925923.472707595
              ],
              [
                1595807.836191182,
                4925924.792309269
              ],
              [
                1595807.7427770847,
                4925924.989689725
              ],
              [
                1595806.6471004162,
                4925924.471730367
              ],
              [
                1595800.8168379439,
                4925921.715610693
              ],
              [
                1595800.729585567,
                4925921.900643843
              ],
              [
                1595799.5710073684,
                4925921.352716694
              ],
              [
                1595797.4540231074,
                4925920.296225771
              ],
              [
                1595795.3732872137,
                4925919.312589556
              ]
            ]
          ]
        },
        "properties": {
          "FID": 73,
          "number_of_stories_above_ground": 2,
          "name": "B7360",
          "floor_area": 4075.62627105,
          "footprint_area": 1358.54209035,
          "number_of_stories": 3,
          "number_of_bedrooms": 3,
          "attic_type":"attic - vented",
          "foundation_type": "basement - conditioned",
          "roof_type": "Gable",
          "number_of_occupants": 3,
          "system_type": "Residential - furnace and no cooling",
          "heating_system_fuel_type": "natural gas",
          "building_type":"Single-Family Detached",
          "year_built": 1980,
          "id": "1502",
          "type": "Building",
          "building_status": "Existing",
          "footprint_perimeter": 167.897455918,
          "emissions": true,
          "number_of_residential_units": 3,
          "exterior_lighting_zone": "3 - All Other Areas",
          "emissions_future_subregion": "RFCEc",
          "emissions_hourly_historical_subregion": "New York",
          "emissions_annual_historical_subregion": "RFCE",
          "emissions_future_year": "2022",
          "emissions_hourly_historical_year": "2019",
          "emissions_annual_historical_year": "2019",
          "template": "Residential IECC 2018 - Customizable Template Sep 2020"
        }
      }
    ]
  }

**Comment by kflemin** [comment]
the issue is with your weather file being outside of the US. In the baseline mapper (mappers/Baseline.rb) there is a function that looks up climate zone from wmo # in the weather file in order to do lookups for the residential workflow. We do not have a mapping of wmo to climate zone for locations outside of the US, therefore you are getting a crash there around line 901.  

You could change the climate zone to one within the US.  You could also modify the baseline mapper to use the climate_zone that is defined within the project field of the geojson file.

Another change I made was to move the emissions fields to the project section rather than have it in the individual features. In UO 0.8.1 and above we have moved away from defining these fields at the feature level in favor of defining them once at the project level.

**Comment by Francesca-urbanplanner** [comment]
Thank you for your help, I ve updated it. 
Another question: in the run command, there s no run -r (for running with REopt functionalities). How can I add it?

**Comment by Francesca-urbanplanner** [comment]
![image](https://user-images.githubusercontent.com/108810715/178856582-e19bb8ad-e837-4238-ba88-2158cc65345d.png)

**Comment by kflemin** [comment]
once you have made a reopt scenario (with create -r ...), and run the reopt scenario the same way that regular scenarios are run, you will then post-process the scenario with the --default post processor.  At that point you can run the additional reopt post-process functionality with either the --reopt-feature or --reopt-scenario flags.  (REopt is a postprocessor that runs after the "run" command)

**Comment by Francesca-urbanplanner** [comment]
and is there any field to specifically include in the feature file for PV (and then REopt simulation) to run the base_assumption scenario?

**Comment by kflemin** [comment]
If you have existing PV in your community, you can add it to the feature file as shown in this file: https://raw.githubusercontent.com/urbanopt/urbanopt-cli/develop/example_files/example_project_with_PV.json. There is an example of community PV and ground mount PV in that file.  

If you just want to explore adding PV to the community, all you need is the existing featurefile and a "REopt" scenario (which would have an extra column in its scenario CSV file pointing to which REopt assumptions file to use).  But that's all you need.

**Comment by Francesca-urbanplanner** [comment]
thank you again for your help!
while I was customising the reopt .json files, I built a scenario with GHP, changing the .csv scenario file in the REopt column. 
However, the results in the scenario optimisation (.csv) appear always the same, even if I created an assumption file with heat pump. Is there by chance any other data which need to be changed before running and optimasing the scenario?

**Comment by kflemin** [comment]
We have not yet implemented GHP in URBANopt.  You could look at this page for all of the possible configurations you can add to your REopt assumptions file: https://developer.nrel.gov/api/reopt/stable/help?API_KEY=DEMO_KEY

**Comment by Francesca-urbanplanner** [comment]
Hello again!
The REopt optimisation of my project led to some strange results because the PV production is higher in winter months rather than summer period, which is something not feasible for Buffalo. I've tried many times to launch the simulations, but results are always similar. If you have any idea, which kind of problem could it be?

**Comment by Francesca-urbanplanner** [comment]
1. I am having another issue, but this time with the Open DSS functionality
![image](https://user-images.githubusercontent.com/108810715/183540326-e54a3fdc-eba2-4f60-8ba3-857fc873db30.png)

**Comment by kflemin** [comment]
can you type "pip3 -V" on the command line? Does that command work or give you an error? you may not have pip installed correctly...

**Comment by Francesca-urbanplanner** [comment]
I ve tried and python is installed correctly. Could it be some problems in the installation of urbanipt?
Another question: the REopt optimisation of my project led to some strange results because the PV production is higher in winter months rather than summer period, which is something not feasible for Buffalo. I've tried many times to launch the simulations, but results are always similar. If you have any idea, which kind of problem could it be?

**Comment by kflemin** [comment]
1. from the error message above it seems that python3 is installed correctly but perhaps not pip3? It's a tough thing to debug remotely, but if you are sure that pip3 is installed and available (and that urbanopt-ditto-reader is also installed), you can try to call the urbanopt-ditto-reader CLI directly. Instructions can be found in the README on this page: https://github.com/urbanopt/urbanopt-ditto-reader

2. for the REopt PV production issue, I have rerun our example project which is located in Buffalo and the results we are getting show greater PV production in the summer months. It is perhaps a configuration issue on your particular project. Are you using the charts created by the "visualize" command to determine this? You can double check the REopt assumptions file you are using, there is perhaps a utility rate structure in there that is causing this issue? Feel free to send over your files and I can try to replicate your results.
![Screen Shot 2022-08-17 at 12 12 48 PM](https://user-images.githubusercontent.com/2205659/185216724-0e4fb0df-d2cf-43a8-8a74-ec76e715b493.png)

**Comment by Francesca-urbanplanner** [comment]
1. thank you, I will
2. I've tried again and results have the same trend. I don't know if it is the assumption file because I ve tried also with the default one (base_assumptions.json) and problem was the same. The zip file with feature, assumption and reopt scenario is attached here. The weather file is the default one from Buffalo. Thank you so much for your help
[SemiDetached_block.zip](https://github.com/urbanopt/urbanopt-cli/files/9365656/SemiDetached_block.zip)

**Comment by Francesca-urbanplanner** [comment]
by the way, I think that the main issue with opendss is the following one
![image](https://user-images.githubusercontent.com/108810715/185651426-e0aaa083-ea8b-4c6f-83de-e8fae2114b8b.png)

**Comment by kflemin** [comment]
Hello @Francesca-urbanplanner, 
I had a chance to look at your project and here are a few thoughts:
1. I had to change the # of bedrooms on a couple of buildings since they were giving me an error during the "run" step... The number of bedrooms that gets fed into the simulation on the back end is the number of bedrooms you entered in the geojson file divided by the number of units that you enter in that same file. In a few cases that number calculated to 0 (for example 3/4). I just increased the number of bedrooms arbitrarily just to get it to run.
2. I think you have an issue with the coordinates of the features in the geojson file and may need to recalculate them.  the GeoJSON file you sent me is not "valid".  A couple of resources to help are https://geojsonlint.com/ (where you can enter the contents of your file to determined if it is valid or not), and https://geojson.io/ (which you can use to visualize the features in your file).

Finally, on the opendss issue: I didn't notice any electrical features in your geojson file. Take a look at the "electric example project by creating a project with the --electric flag and inspecting the geojson file. You'll see that there are electrical features in there such as transformers, electrical connectors, etc. These features are needed for the opendss analysis.  More documentation on the opendss workflow can be found at https://docs.urbanopt.net/workflows/opendss/opendss.html.

Hope this helps!

**Comment by Francesca-urbanplanner** [comment]
Hello @kflemin 
1. yes. I've actually already modified it: i think i sent you the previous file version
2. thank you. It's weird because i used the spatial system mentioned in the documentation to create to geojson file on gis
3. i sent you the file without the electrical newtork. the error i am having with opendss is the current one
![image](https://user-images.githubusercontent.com/108810715/186254947-8cd418c7-b53d-440d-8995-5e03a5419a93.png)

**Comment by kflemin** [comment]
That error isn't very informative unfortunately. if you want to send me the geojson file with the electrical network I can try to run it locally. you can also email me the file...if you type my name + NREL in google you can find my email address pretty quick :)
