### ISSUE TITLE
Clarify how to upgrade python dependencies

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-cli#367]
**Is your feature request related to a problem? Please describe.**
If a python dependency (e.g. disco, or GMT) upgrade their released version, I'd like to take advantage of that

**Describe the solution you'd like**
Include a cli flag to the install_python command to upgrade dependencies

**Describe alternatives you've considered**
Simply provide documentation for how to do it manually

**Comment by kflemin** [comment]
do we need to version the python dependencies and install specific versions depending on what version of the CLI we are using?
