### ISSUE TITLE
Create CLI call to GMT to generate Modelica DES files

### ISSUE THREAD

**Issue by JingWang-CUB** [urbanopt/urbanopt-cli#393]

**Comment by vtnate** [comment]
Are you looking for something like https://github.com/urbanopt/urbanopt-cli/blob/develop/lib/uo_cli.rb#L409-L425? If there are additional cli calls we need, I'm happy to talk about it.

**Comment by mitchute** [comment]
Looks like this is already in place. Closing. Will reopen if needed.
