### ISSUE TITLE
Spring 2023 update to OpenStudio 3.6.0/EnergyPlus 23.1.0/Ruby 3.1.3 (E)

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#410]

**Comment by vtnate** [comment]
Upgrading to Ruby 3 was postponed in OpenStudio until a future update. The current [OpenStudio compatibility matrix](https://github.com/NREL/OpenStudio/wiki/OpenStudio-SDK-Version-Compatibility-Matrix) shows dependency versions. [Version 0.10.0](https://github.com/urbanopt/urbanopt-cli/releases/tag/v0.10.0) of URBANopt supports OS 3.6.1.
