### ISSUE TITLE
Error while using `install_python` on windows

### ISSUE THREAD

**Issue by tanushree04** [urbanopt/urbanopt-cli#431]
### Expected behavior

`install_python` should install a python in the example_files/python_deps folder

### Actual behavior
When using gitbash and `bundle exec uo install_python` the following error is seen : 

$ bundle exec uo install_python
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!

Installing python and dependencies
Checking system.....
Python paths have not yet been initialized with URBANopt.
Installing python...
ERROR installing python dependencies: Set-ExecutionPolicy : Access to the registry key 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\PowerShell\1\ShellIds\Microsoft.PowerShell' is denied. To change the execution policy for 
the default (LocalMachine) scope,
start Windows PowerShell with the "Run as administrator" option. To change the execution policy for the current user, run "Set-ExecutionPolicy -Scope CurrentUser".
At line:1 char:1
+ Set-ExecutionPolicy -ExecutionPolicy Unrestricted
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Set-ExecutionPolicy], UnauthorizedAccessException
    + FullyQualifiedErrorId : System.UnauthorizedAccessException,Microsoft.PowerShell.Commands.SetExecutionPolicyCommand
,
Installing urbanopt-ditto-reader...

When using Powershell and `bundle exec uo install_python` the following error is seen : 

Installing python and dependencies
Traceback (most recent call last):
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/uo:23:in `<main>'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/bin/uo:23:in `load'
        10: from C:/urbanopt-cli/bin/uo:3:in `<top (required)>'
         9: from C:/urbanopt-cli/bin/uo:3:in `require'
         8: from C:/urbanopt-cli/lib/uo_cli.rb:57:in `<top (required)>'
         7: from C:/urbanopt-cli/lib/uo_cli.rb:58:in `<module:URBANopt>'
         6: from C:/urbanopt-cli/lib/uo_cli.rb:1220:in `<module:CLI>'
         5: from C:/urbanopt-cli/lib/uo_cli.rb:1034:in `install_python_dependencies'
         4: from C:/urbanopt-cli/lib/uo_cli.rb:961:in `check_python'
         3: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:281:in `capture3'
         2: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:101:in `popen3'
         1: from C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `popen_run'
C:/Ruby27-x64/lib/ruby/2.7.0/open3.rb:213:in `spawn': No such file or directory - C:/urbanopt-cli/example_files/python_deps/python-3.10/python.exe -V (Errno::ENOENT)

### To Reproduce

Use `install_python` command

### Additional context

Windows

**Comment by vtnate** [comment]
Closed by #458
