### ISSUE TITLE
Add detailed OSM workflow to example project

### ISSUE THREAD

**Issue by kflemin** [urbanopt/urbanopt-cli#44]
have one of the buildings use a detailed OSM (in geojson) and update mappers to detect this situation and handle it correctly.

I think @tanushree04 has this work on a fork of the example project.

**Comment by tanushree04** [comment]
@kflemin On my [fork](https://github.com/tanushree04/urbanopt-example-geojson-project/tree/geojson_detailed_osm_workflow), I have used a modified version of the building_properties schema, that only requires the building id, type, name, geometry as required properties. However the urban_geometry_creation measure that creates buildings from the geojson file requires more [properties](https://github.com/urbanopt/urbanopt-geojson-gem/blob/a472449babdbce8a3a899374b0d535a1b5538eae/lib/urbanopt/geojson/schema/building_properties.json#L195). 
Should I add all the additional properties in the geojson file even in case a detailed osm is present?

**Comment by kflemin** [comment]
@tanushree04, I think that if the properties are not 'really' required (i.e. that there is an urbanopt workflow that can be run with a minimal set of inputs), then either:
1. they should be marked as optional and the validation will only check for the minimal set (and maybe check for the larger set during the 2nd validation call, although that will be hard to track what is required and what is not)
or 
2. leave them as required but modify the validation process to only require the smaller set when a detailed osm is passed in.  

I think 2 may be more manageable as you'll only need to track the smaller set in the code and the larger set can be as is in the schema.

what do you think?

**Comment by tanushree04** [comment]
@kflemin , yes the 2nd approach makes sense. I added validation in the geojson gem only for the smaller set when the detailed osm is passed in (https://github.com/urbanopt/urbanopt-geojson-gem/pull/52/files#r383552345)
