### ISSUE TITLE
Error with EMS sensor names in BuildResidentialModel measure

### ISSUE THREAD

**Issue by JingWang-CUB** [urbanopt/urbanopt-cli#450]
### Expected behavior

EMS sensor names for each individual unit should be initialized correctly before they are called in the EMS programs.

### Actual behavior

Wrong sensor names were used in the EMS programs causing "sensor not initialized" errors for residential buildings with more than one units.
![image](https://github.com/urbanopt/urbanopt-cli/assets/31628742/74228d99-3c76-4558-a9c8-fe73271a0bf7)
This is potentially caused by line 468 in the measure:
![image](https://github.com/urbanopt/urbanopt-cli/assets/31628742/f7e27cd6-775d-441c-ac90-20230dba4bc1)

### To Reproduce

Run a Single Family Attached building with more than one units in UO CLI. The heating system type can be "residential - boiler with no cooling". UO version is 0.10.0 with OS-HPXML 1.6.0, but this should still exist in the latest UO version.

### Additional context

Windows 10.

**Comment by kflemin** [comment]
@joseph-robertson

**Comment by JingWang-CUB** [comment]
Upgrading to UO 0.11.1 solved the problem.
