### ISSUE TITLE
uo des_create issue

### ISSUE THREAD

**Issue by glinn07** [urbanopt/urbanopt-cli#480]
### Expected behavior

When I run uo des_create I expect the following line to work:

uo des_create -y systemparam.json -f example_project.json -n m3

### Actual behavior

I receive the following output with an error at the end:

> gl@hl-m2` Working % uo des_create -y sampleUO/systemparam.json -f sampleUO/example_project.json -n sampleUO/m3
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Checking system.....
> ...python found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/python
> ...pip found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/pip
> DEPENDENCIES RETRIEVED FROM FILE: [{:name=>"ThermalNetwork", :version=>"0.2.5"}, {:name=>"urbanopt-ditto-reader", :version=>"0.6.4"}, {:name=>"NREL-disco", :version=>"0.5.1"}, {:name=>"geojson-modelica-translator", :version=>"0.7.0"}]
> ...ThermalNetwork found with specified version 0.2.5
> ...urbanopt-ditto-reader found with specified version 0.6.4
> ...NREL-disco found with specified version 0.5.1
> ...geojson-modelica-translator found with specified version 0.7.0
> Usage: uo_des create-model [OPTIONS] SYS_PARAM_FILE GEOJSON_FEATURE_FILE
>                            [PROJECT_PATH]
> Try 'uo_des create-model -h' for help.
> 
> Error: Got unexpected extra argument (Park/Working/sampleUO/m3)

I tried using the --des-name flag and got the same issue

If I try to run without specifying the des directory name I get the following:

> gl@hl-m2 Working % uo des_create -y sampleUO/systemparam.json -f sampleUO/example_project.json        
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Error: option --des-name must be specified.

### Additional context

Mac, running uo cli 0.13.0

**Comment by vtnate** [comment]
I think it is looking for a path, so instead of passing `-n m3`, try `-n ./m3`.

Yes, we currently require a model name name, so that `--des-name must be specified` is the expected behavior. However, I don't think we strictly need to require that; perhaps we'll relax that in the next version. It should be capable of providing a name by itself.

**Comment by glinn07** [comment]
Thanks Nate! Unfortunately didn't work:

> gl@HL-M2 Working % uo des_create -y sampleUO/systemparam.json -f sampleUO/example_project.json --des-name ./m3
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Checking system.....
> ...python found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/python
> ...pip found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/pip
> DEPENDENCIES RETRIEVED FROM FILE: [{:name=>"ThermalNetwork", :version=>"0.2.5"}, {:name=>"urbanopt-ditto-reader", :version=>"0.6.4"}, {:name=>"NREL-disco", :version=>"0.5.1"}, {:name=>"geojson-modelica-translator", :version=>"0.7.0"}]
> ...ThermalNetwork found with specified version 0.2.5
> ...urbanopt-ditto-reader found with specified version 0.6.4
> ...NREL-disco found with specified version 0.5.1
> ...geojson-modelica-translator found with specified version 0.7.0
> Usage: uo_des create-model [OPTIONS] SYS_PARAM_FILE GEOJSON_FEATURE_FILE
>                            [PROJECT_PATH]
> Try 'uo_des create-model -h' for help.
> 
> Error: Got unexpected extra argument (Park/Working/m3)

I also tried running directly within the project directory ("sampleUO") and uo totally crashes in that scenario

**Comment by glinn07** [comment]
Hi @vtnate I think I figured out the root of the issue

I am creating an example project but I am not specifying that it is a ghe project

I run the followings sequence of commands

   uo create -p sampleUO
			
   uo run -s sampleUO/baseline_scenario.csv -f sampleUO/example_project.json
			
   uo des_params -y sampleUO/sys_params.json -s sampleUO/baseline_scenario.csv -f sampleUO/example_project.json -t 4G

These all work. In my mind I've created a plain vanilla set of example file and a hot water/cold water 4G system

But when I run uo des_create I get the following:

> gl@HL-M2 Working % uo des_create -y sampleUO/sys_params.json -f sampleUO/example_project.json -n sampleUO/mm5
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Checking system.....
> ...python found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/python
> ...pip found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/pip
> DEPENDENCIES RETRIEVED FROM FILE: [{:name=>"ThermalNetwork", :version=>"0.2.5"}, {:name=>"urbanopt-ditto-reader", :version=>"0.6.4"}, {:name=>"NREL-disco", :version=>"0.5.1"}, {:name=>"geojson-modelica-translator", :version=>"0.7.0"}]
> ...ThermalNetwork found with specified version 0.2.5
> ...urbanopt-ditto-reader found with specified version 0.6.4
> ...NREL-disco found with specified version 0.5.1
> ...geojson-modelica-translator found with specified version 0.7.0
> Usage: uo_des create-model [OPTIONS] SYS_PARAM_FILE GEOJSON_FEATURE_FILE
>                            [PROJECT_PATH]
> Try 'uo_des create-model -h' for help.
> 
> Error: Got unexpected extra argument (Park/Working/sampleUO/mm5)

I think maybe the issue is with 4G systems??? Because if I follow the path of the 5g_ghe system it works no problem...
