### ISSUE TITLE
Gathering results (post-processing) should provide scenario-level results in a database file

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-cli#49]
LB Tools would strongly prefer to use sql to read results at the scenario level. Can we make that happen?

**Comment by vtnate** [comment]
This is in progress. Plan is to read existing database results for each feature, aggregate, and dump into a new database file at scenario level. Have not settled on the time/manner to call this.

**Comment by kflemin** [comment]
The structure of the new database should be exactly the same as the structure of the individual datapoint database (so if you're pulling from ReportData, you have to dump into ReportData in the new database).  thanks!

**Comment by vtnate** [comment]
Ahh, good to know the table names must match too.
