### ISSUE TITLE
Recommend using absolute paths

### ISSUE THREAD

**Issue by vtnate** [urbanopt/urbanopt-cli#83]
**Is your feature request related to a problem? Please describe.**
When using urbanopt commands from inside the project folder, many warning are printed to the screen.

**Describe the solution you'd like**
Ideally those warnings would not be printed. A work-around would be to recommend users call absolute paths from outside the project folder, so the project folder Gemfile doesn't get confused.

**Comment by brianlball** [comment]
i get this a bunch:

C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/urbanopt-cli-0.2.2/developer_nrel_key.rb:31: warning: already initialized constant DEVELOPER_NREL_KEY
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/urbanopt-reopt-0.2.0/developer_nrel_key.rb:31: warning: previous definition of DEVELOPER_NREL_KEY was here

**Comment by kflemin** [comment]
@brianlball this is a known issue and shouldn't hurt anything
https://docs.urbanopt.net/developer_resources/known_issues.html (item #4)
