### ISSUE TITLE
reopt dependency not installed

### ISSUE THREAD

**Issue by brianlball** [urbanopt/urbanopt-cli#85]
fresh install of urbanopt-cli doesnt get the ubranopt-reopt gem for some reason:

![image](https://user-images.githubusercontent.com/2235296/78920163-37c74500-7a50-11ea-9d8c-fc0d827dce45.png)

Windows 10
ruby 2.2.4p230

**Comment by kflemin** [comment]
the reopt gem needs to be added to the gemspec file
